production:
  cloud_name: 'dvreazuho'
  api_key: '119749114112574'
  api_secret: 'rjKjKY_VkHRyjb3LI98AF799NuU'

development:
  cloud_name: 'dvreazuho'
  api_key: '119749114112574'
  api_secret: 'rjKjKY_VkHRyjb3LI98AF799NuU'
